#!/usr/bin/env python

import sys
import os
import csv

path = ""
opts = []

if len(sys.argv) == 1:
    path = raw_input("Enter your path where your files are located (Ex: /Users/JohnCena/Downloads/)\n>")

else:
    path = sys.argv[-1]
    for arg in sys.argv:
        if arg.startswith('-'):
            for character in arg[1:]:
                opts.append(character)
        else:
            path = arg

if 'h' in opts:
    print "-r Recurisvely search and convert tab-delimited .txt files in the given directory"
    print "-d Delete the .txt files after conversion"
    sys.exit(0)


def convert_text_file(text_file, csv_file):
    with open(text_file, 'rb') as txt_file, open(csv_file, 'wb') as new_csv:
        dialect = csv.Sniffer().sniff(txt_file.read(1073741824), delimiters='\t|,;')
        txt_file.seek(0)
        reader = csv.reader(txt_file, dialect)
        out_csv = csv.writer(new_csv)
        for row in reader:
            out_csv.writerow(row)




def convert_text_files(local_path, _user_called=True, _total_count=0.0, _count=0):
    if os.path.isdir(local_path):
        # Find total # of files
        if _user_called:
            print "Counting total items"
            for dirpath, dirname, filenames in os.walk(local_path):
                for filename in filenames:
                    if filename.endswith(".txt"):
                        _total_count += 1
            print "Converting %d items..." % _total_count

            # Search for the items within the directory
        for filename in os.listdir(local_path):
            # if the directory exists, run method recursively
            new_path = os.path.join(local_path, filename)

            if os.path.isdir(new_path) and 'r' in opts:
                _count = convert_text_files(new_path, False, _total_count, _count)

            # if the file is a .txt file, convert to csv format
            elif filename.endswith('.txt'):
                # create the csv file
                csv_filename = local_path + '/' + filename[:-4] + '.csv'

                # Check the txt file to find what type of delimiter
                text_path = os.path.join(local_path, filename)
                convert_text_file(text_path, csv_filename)
                    if 'd' in opts:
                        os.remove(text_path)
                _count += 1

            ratio = (_count / _total_count)
            progress_length = int(ratio * 40)
            sys.stdout.write(
                '\r[' + ("=" * progress_length) + " " * (40 - progress_length) + ']%d' % (ratio * 100) + '%')
            sys.stdout.flush()

        if _user_called:
            print "\nConversion finished. \n" + str(_count) + " files converted"

        return _count

    elif os.path.isfile(path):
        with open(path[:-4] + ".csv", 'wb') as csv_file:
            convert_text_file(csv_file)
            if 'd' in opts:
                os.remove(path)
    else:
        print "Neither file nor directory"


print "Starting Conversion"

convert_text_files(path)
